### ISSUE TITLE
ImportError: cannot import name 'load_lexicon' from 'riveter.riveter'

### ISSUE THREAD

**Issue by Bhuvanesh-Verma** [maartensap/riveter-nlp#2]
First of all, thanks for this useful tool. I am trying to analyse website text of some organisations using Riveter. After installation I end up with ImportError while importing riveter.

I found that `load_lexicon` method is commented out in [riveter.py](https://github.com/maartensap/riveter-nlp/blob/main/riveter/riveter.py#L96) but is still being referenced in [__init__.py](https://github.com/maartensap/riveter-nlp/blob/8a526d7bf1ac7594ad80536eb367e5c010eaf3d6/riveter/__init__.py#L3) which results in **ImportError**.

```python
    # def load_lexicon(self, label):
    #     if label in ['power', 'agency']:
    #         self.load_sap_lexicon(label)
    #     else:
    #         self.load_rashkin_lexicon(label)
```

For local installation, it worked for me by updating __init__.py as following,

```python
from .riveter import (
  Riveter
)
```
 but I wanted to integrate Riveter in a web app, so it would be great if this issue is fixed. 

Thanks.

**Comment by maria-antoniak** [comment]
Hi, sorry to be slow! I wasn't able to replicate this error, but I've removed `load_lexicon` from `init.py`. Let me know if you still experience problems!
