### ISSUE TITLE
cannot import name 'load_rashkin_lexicon'

### ISSUE THREAD

**Issue by julianeugarten** [maartensap/riveter-nlp#3]
I'm pretty new to Python so bear with me. I set up the RiveterEnv as instructed, then imported libraries as instructed. When I get to:

`from riveter import Riveter`

I get the following error message: 'ImportError: cannot import name 'load_rashkin_lexicon' from 'riveter.riveter' (/Users/[my-username]/riveter-nlp/riveter/riveter.py)'

What am I doing wrong?

Thanks so much for your help.

**Comment by maria-antoniak** [comment]
Hi there! One quick solution would be to use our Colab notebook instead of your local computer. That way, you just need to upload your data and don't need to set up the Python environment. You can see the Colab notebook [here](https://colab.research.google.com/drive/19akZ2Qu7uva8jOsc49e_2HJmDo88WAXm?usp=sharing). Create a copy of the notebook (`File`-->`Save a copy in Drive`) and then edit as you wish. 

If you prefer to run on your local computer, I'm not sure what's going wrong but it looks like your code can't find Riveter. Could you share the folder and file structure of your project?

**Comment by julianeugarten** [comment]
Thanks so much for the quick response. 

Using the Colab notebook, I run into problems with the required amount of memory, which is why I decided to go the local route. 

I think you might be right because the full error reads:

`ImportError: cannot import name 'load_rashkin_lexicon' from 'riveter.riveter' (/Users/julia.neugarten/riveter-nlp/riveter/riveter.py)`

I have the Github Repo in the following path: Macintosh HD > Users > [me] > riveter-nlp. I'm sure I'm overlooking something, but that looks to me like the right path.

Within the riveter-nlp folder, I have all the files from your repo plus a folder with my own .txt files and, outside of that folder, a .csv to which I have added the text of each of my stories with an ID. My aim is to feed this csv to Riveter as a pandas dataframe, like you did in the NYT Obits example.

As a sidenote, I love your work on story detection with online communities!

**Comment by julianeugarten** [comment]
Update: I was able to solve this problem by moving everything (code and data) into the riveter folder. Thanks so much for your help though!

**Comment by maria-antoniak** [comment]
Sorry to be slow, and glad you figured it out! Yes, that's why I was asking about the folder structure; everything should be in the Riveter folder. Let me know if you have any further questions, and we'd love to know how you end up using Riveter!

**Comment by ghost** [comment]
I am running into a similar issue, but I am working with the code in Rstudio. The error code I receive is: riveter <- import("riveter")
Error in py_module_import(module, convert = convert) : 
  ImportError: cannot import name 'load_rashkin_lexicon' from 'riveter.riveter' (/opt/anaconda3/envs/riveterEnv/lib/python3.9/site-packages/riveter/riveter.py)
Run `reticulate::py_last_error()` for details. Here is the folder: 
<img width="771" alt="Screenshot 2024-08-07 at 3 50 55 PM" src="https://github.com/user-attachments/assets/57a82b85-f3a6-4dc5-9342-be82b956d09d"> 
And here is my code: 
[RStudio.pdf](https://github.com/user-attachments/files/16534942/RStudio.pdf)

**Comment by maria-antoniak** [comment]
Hi, I've replied to the issue you opened, so let's keep the discussion in that thread, as I believe this is a separate problem related to RStudio.
