### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by ghost** [maartensap/riveter-nlp#8]
Hi, 
Does the package require Python 3.9 **specifically**, or does it require a **minimum** version of 3.9? 

Thank you!

**Comment by maria-antoniak** [comment]
We've only tested it with Python 3.9, but I don't know of any reason that a newer version wouldn't work. I strongly recommend that you create a new Python environment (e.g. by using conda) that follows the instructions provided here: https://github.com/maartensap/riveter-nlp?tab=readme-ov-file#installation
